// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtsdq2aUnz_H4p7mgrioBjIn0DEThn5bs',
    appId: '1:964004169514:web:a0e5212160787c168f4053',
    messagingSenderId: '964004169514',
    projectId: 'mindflow-dee57',
    authDomain: 'mindflow-dee57.firebaseapp.com',
    storageBucket: 'mindflow-dee57.firebasestorage.app',
    measurementId: 'G-49FCWX90Z6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBotvFTDOFNINLE8ArRHHiXUzNWTb6Vdk4',
    appId: '1:964004169514:android:d881b2f159bdaeb08f4053',
    messagingSenderId: '964004169514',
    projectId: 'mindflow-dee57',
    storageBucket: 'mindflow-dee57.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1-s7Hx_JXs6UlsG8GQm413FkgVnZeAV8',
    appId: '1:964004169514:ios:5909187f6d07d6d48f4053',
    messagingSenderId: '964004169514',
    projectId: 'mindflow-dee57',
    storageBucket: 'mindflow-dee57.firebasestorage.app',
    iosBundleId: 'com.chalaka.mindflowApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1-s7Hx_JXs6UlsG8GQm413FkgVnZeAV8',
    appId: '1:964004169514:ios:5909187f6d07d6d48f4053',
    messagingSenderId: '964004169514',
    projectId: 'mindflow-dee57',
    storageBucket: 'mindflow-dee57.firebasestorage.app',
    iosBundleId: 'com.chalaka.mindflowApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtsdq2aUnz_H4p7mgrioBjIn0DEThn5bs',
    appId: '1:964004169514:web:af2e7e23b6e7b53b8f4053',
    messagingSenderId: '964004169514',
    projectId: 'mindflow-dee57',
    authDomain: 'mindflow-dee57.firebaseapp.com',
    storageBucket: 'mindflow-dee57.firebasestorage.app',
    measurementId: 'G-NX8TZSXTGD',
  );
}
